#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  nadduli-alx-frontend
        bind *:80
        mode http
        default_backend nadduli-alx-backend
backend nadduli-alx-backend
        balance roundrobin
        server 413-web-01 35.231.87.217:80 check
        server 335-web-02 3.239.113.227:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart